# 유저 생성
CREATE USER 'BOOOMS'@'LOCALHOST' IDENTIFIED BY '1111';
# 실행: CTRL + ENTER
# SQL문 작성 시 절대 ';'로 종료.
CREATE USER 'BOOOMS_REMOTE'@'%' IDENTIFIED BY '1111';

# 생성된 계정 확인
SELECT USER, HOST FROM MYSQL.USER;

# 계정에 권한 부여
# GRANT 부여할 권한 ON 대상 테이블 TO 권한 부여할 계정
GRANT ALL PRIVILEGES ON *.* TO 'BOOOMS'@'LOCALHOST';
GRANT ALL PRIVILEGES ON *.* TO 'BOOOMS_REMOTE';
#                       *.* >> DB.TABLE

#DB 생성
CREATE DATABASE TEST_DB;

CREATE DATABASE HR;

SHOW DATABASES;
# GRANT ALL PRIVILEGES ON TEST_DB.CUSTOMER TO PLAYDATA@'%'; 

DROP DATABASE HR;

USE TEST_DB;

# 테이블 생성
CREATE TABLE MEMBER(
	ID VARCHAR(10)  PRIMARY KEY,  -- 최대 10글자
    PASSWORD VARCHAR(10) NOT NULL,  -- NOT NULL ( == 필수 입력)
    NAME VARCHAR(50) NOT NULL,
    POINT INT DEFAULT 1000,  -- 값을 넣지 않으면 1000을 기본값으로 입력
    EMAIL VARCHAR(100) NOT NULL UNIQUE,  -- UNIQUE: 중복값을 허용하지 않음
    AGE INT CHECK(AGE > 1),
    JOIN_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  -- DEFAULT CURRENT_TIMESTAMP: 값이 INSERT 되는 시점을 저장.
);


# 테이블 조회
SHOW TABLES;

# 테이블의 컬럼정보 조회
DESC MEMBER;

# 테이블 삭제
DROP TABLE IF EXISTS AA;

DROP TABLE IF EXISTS MEMBER;

#########DML##########

# INSERT EXMAPLE

# 모든 컬럼에 값을 넣을 경우 컬럼명 생략
INSERT INTO MEMBER VALUES(
	'SCOTT',
    'TIGER',
    '맥토미니',
    2000,
    'SCOTT@MU',
    '26',
    '2025-04-03 12:17:46'
);

INSERT INTO MEMBER (ID, PASSWORD, NAME, EMAIL)
VALUES("JAMES", "1111", 'SMITH', 'DFJDF@DD.COM');

SELECT * FROM MEMBER;

INSERT INTO MEMBER (ID, PASSWORD, NAME, POINT, EMAIL)
VALUES ('BOOOMS', '1111', '범석', 99999, 'TOP@SECRET.COM');

INSERT INTO MEMBER (ID, PASSWORD, NAME, EMAIL, AGE)
VALUES("ID-400", "1111", 'COBRA', 'PWHWF@NXOS.COM', 1);



